name: Auto Version Bump and Build

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get the latest tag (or default to v1.0.0 if none exists)
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next version
        id: next_tag
        run: |
          latest_version=${{ env.latest_tag }}
          IFS='.' read -r -a parts <<< "${latest_version//v/}"
          new_version="v${parts[0]}.$((parts[1] + 1)).${parts[2]}"
          echo "next_version=$new_version" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag ${{ env.next_version }}
          git push origin ${{ secrets.GH_TOKEN }} ${{ env.next_version }}  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (with BUILDX_GIT_INFO=false)
        env:
          BUILDX_GIT_INFO: false  # Добавлена переменная окружения
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service-shsh:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/auth-service-shsh:latest ${{ secrets.DOCKER_USERNAME }}/auth-service-shsh:${{ env.next_version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-shsh:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-shsh:${{ env.next_version }}

      - name: Update latest tag
        run: |
          git tag -f latest ${{ env.next_version }}
          git push origin ${{ secrets.GH_TOKEN }} latest